// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlkcHRIOWFrMHH85avDIBmn4AC0P5MlM',
    appId: '1:1049970791173:web:6df339eee6640b2ac3dd6c',
    messagingSenderId: '1049970791173',
    projectId: 'mad-proj-vol-app',
    authDomain: 'mad-proj-vol-app.firebaseapp.com',
    storageBucket: 'mad-proj-vol-app.firebasestorage.app',
    measurementId: 'G-E07EZ4FTCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAb2jSgKan8a5mCZNd_wN-vU0Bk4mpA_4',
    appId: '1:1049970791173:android:64d433bfd2f33a6ec3dd6c',
    messagingSenderId: '1049970791173',
    projectId: 'mad-proj-vol-app',
    storageBucket: 'mad-proj-vol-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdzjA2tX3u1smILCDV1ZoQGGG1TYkOMRQ',
    appId: '1:1049970791173:ios:b80e893ef0b43e90c3dd6c',
    messagingSenderId: '1049970791173',
    projectId: 'mad-proj-vol-app',
    storageBucket: 'mad-proj-vol-app.firebasestorage.app',
    iosClientId: '1049970791173-uirlldp32lteo9kb6202bp9umehjhuhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.madFlutterAppVol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdzjA2tX3u1smILCDV1ZoQGGG1TYkOMRQ',
    appId: '1:1049970791173:ios:b80e893ef0b43e90c3dd6c',
    messagingSenderId: '1049970791173',
    projectId: 'mad-proj-vol-app',
    storageBucket: 'mad-proj-vol-app.firebasestorage.app',
    iosClientId: '1049970791173-uirlldp32lteo9kb6202bp9umehjhuhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.madFlutterAppVol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTlkcHRIOWFrMHH85avDIBmn4AC0P5MlM',
    appId: '1:1049970791173:web:9eb858ed53b44fe1c3dd6c',
    messagingSenderId: '1049970791173',
    projectId: 'mad-proj-vol-app',
    authDomain: 'mad-proj-vol-app.firebaseapp.com',
    storageBucket: 'mad-proj-vol-app.firebasestorage.app',
    measurementId: 'G-TR1PX6QYKW',
  );

}